#!/bin/bash
#$1 should be --solve-with-PETSc or --solve-with-pardiso

#this should be modified from system to system
inputfile_path=/home/mot_tudor/workspace/unijob/input/beamp.txt
#/home/mot_tudor/workspace/unijob/input/beamp.txt
#/home/mot_tudor/Downloads/mtu_matrices/job3.sti
outputfile_path=/home/mot_tudor/workspace/unijob/input/timing_results.txt
exec_name=time_solvers

#create output file if it does not exist
touch ${outputfile_path}


mpiexec.hydra -n 1 ./${exec_name}  $1 ${inputfile_path} ${outputfile_path} -mat_type seqaij -pc_type ilu -ksp_converged_reason -ksp_type bcgs 

#-bind-to socket:1
#-ksp_monitor_true_residual ascii:monitor_bgcs.xml:ascii_xml
#TODO tweak gmres restart param, but for default value it does not converge..and tolerance??
#-log_view
#-info
#bind-to core
#-mat_view draw -draw_pause
#-ksp_monitor_lg_residualnorm
#-ksp_monitor_true_residual monitor.txt
#ascii:monitor.txt:
#-mat_view draw -draw_pause 5 
