#!/bin/bash
#$1 should be the name of the compiled program to be ran
#$2 should be number of mpi processes
#$3 should be --solve-with-PETSc or --solve-with-pardiso

#this should be modified from system to system
inputfile_path=/home/mot_tudor/workspace/unijob/input/beamp.txt
outputfile_path=/home/mot_tudor/workspace/unijob/input/timing_results.txt

#create output file if it does not exist
touch ${outputfile_path}

mpiexec -n $2 $1 $3 ${inputfile_path} ${outputfile_path} -ksp_type gmres -ksp_converged_reason -draw_pause 10 -ksp_view -ksp_gmres_restart 200
#TODO tweak gmres restart param, but for default value it does not converge..and tolerance??
#-log_view
#-info
#
