#!/bin/bash

#SBATCH -o /home/hpc/pr63so/ga53lov2/petsc_times.%j.%N.out 
#SBATCH -D /home/hpc/pr63so/ga53lov2/code
#SBATCH -J petsc_times
#SBATCH --get-user-env 
#SBATCH --clusters=mpp2
#SBATCH --nodes=1-1 
#SBATCH --cpus-per-task=8 
#SBATCH --mail-type=end 
#SBATCH --mail-user=ga53lov@tum.de 
#SBATCH --export=NONE 
#SBATCH --time=12:00:00 

./load_modules
touch /home/hpc/pr63so/ga53lov2/timing_results_petsc.txt
cd ~/code
# 28 is the maximum reasonable value for CooLMUC-2 

#this should be modified from system to system
inputfile_path=/naslx/projects/pr63so/ga53lov2/job3.sti
outputfile_path=/home/hpc/pr63so/ga53lov2/timing_results_petsc.txt

mpiexec -n 8 ./time_solvers --solve-with-PETSc ${inputfile_path} ${outputfile_path} -ksp_type gmres -ksp_gmres_restart 200
